apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-deployment
  labels: 
     app: regapp
 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: regapp
 
  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp
        image: <your_ecr_image>
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-registry-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
